### ISSUE TITLE
Can't set video_bandwidth

### ISSUE THREAD

**Issue by christof1977** [l-johnston/rsfsup#1]
Hi,

it seems that I can't set video_bandwidth and resolution_bandwidth. I'm I doing something wrong?
I can read the values:
```
with CommChannel(FSUP_HOST) as fsup:
     fsup.spectrum.bandwidth.video_bandwidth
 
'10.0 MHz'
```

However, as soon as I try to set the value, the following exception occurs:
```
with CommChannel(FSUP_HOST) as fsup:
     fsup.spectrum.bandwidth.video_bandwidth = '3 MHz'
 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/rsfsup/common.py", line 66, in __setattr__
    raise AttributeError(f"can't set '{name}'") from None
AttributeError: can't set 'video_bandwidth'
```

Thanks a lot
Christof

**Comment by l-johnston** [comment]
Hi Christof, the FSUP, by default, sets video bandwidth to automatically
track the resolution bandwidth in the ratio 3:1. With my library you have
two options:
1. Change the resolution bandwidth (RBW) which will change the video
bandwidth to be 3x RBW
2. On the FSUP front panel, navigate to the BW settings and press VIDEO BW
Manual, then you can set video bandwidth independent of RBW

In [1]: from rsfsup import CommChannel
In [2]: cc = CommChannel("10.2.144.11")
In [3]: fsup = cc.get_instrument()
# default RBW and video bandwidth
In [4]: fsup.spectrum.bandwidth.video_bandwidth
Out[4]: '10.0 MHz'
In [6]: fsup.spectrum.bandwidth.resolution_bandwidth
Out[6]: '3.0 MHz'
# change RBW in AUTO mode
In [7]: fsup.spectrum.bandwidth.resolution_bandwidth = "100 kHz"
In [8]: fsup.spectrum.bandwidth.resolution_bandwidth
Out[8]: '100.0 kHz'
In [9]: fsup.spectrum.bandwidth.video_bandwidth
Out[9]: '300.0 kHz'
# Press VIDEO BANDWIDTH MANUAL soft key
In [10]: fsup.spectrum.bandwidth.video_bandwidth = "3 MHz"
In [11]: fsup.spectrum.bandwidth.video_bandwidth
Out[11]: '3.0 MHz'
In [12]: fsup.spectrum.bandwidth.resolution_bandwidth
Out[12]: '100.0 kHz'

Let me know if changing the mode programmatically is an important feature
and I will take a look at it.

Lee

**Comment by christof1977** [comment]
Hi Lee,

thanks for your fast reply. In fact this issue is not related to the FSUP. One can set the VBW independently to RBW like on mostly all available spectrum analyzers. This is what you describe in option two.
I was successful by using the visa commands directly in my code as you use them in your code:
```
fsup._visa.write(f"SENSE{fsup._screen()}:BAND:VID:AUTO OFF")
fsup._visa.write(f"SENSE{fsup._screen()}:BAND:VID 5000")
```
This works perfectly fine, so it seems to happen somewhere in you common.py (see also Traceback above).
For me this is ok so, however, I think it would be nice to have a running lib. Indeed, your work is very valuable!

Cheers
Christof

**Comment by l-johnston** [comment]
@christof1977 It is possible to change the video bandwidth. Upgrade to version 0.1.21

```python
In [1]: from rsfsup import CommChannel
In [2]: cc = CommChannel("10.2.144.11")
In [3]: fsup = cc.get_instrument()
In [4]: fsup.spectrum.bandwidth.resolution_bandwidth
Out[4]: '50.0 kHz'
In [5]: fsup.spectrum.bandwidth.video_bandwidth
Out[5]: '50.0 kHz'
In [6]: fsup.spectrum.bandwidth.rbw_vbw_ratio
Out[6]: 1.0
In [7]: fsup.spectrum.bandwidth.rbw_vbw_ratio = 0.1
In [8]: fsup.spectrum.bandwidth.rbw_vbw_ratio
Out[8]: 0.1
In [9]: fsup.spectrum.bandwidth.resolution_bandwidth
Out[9]: '50.0 kHz'
In [10]: fsup.spectrum.bandwidth.video_bandwidth
Out[10]: '500.0 kHz'
In [11]: fsup.spectrum.bandwidth.video_bandwidth = "3 MHz"
In [12]: fsup.spectrum.bandwidth.video_bandwidth
Out[12]: '3.0 MHz'
```

**Comment by christof1977** [comment]
Thank you very much!
